#!/bin/bash

read -p "Enter first number:" num1
read -p "Enter second number:" num2

add=$((num1 + num2))
sub=$((num1 - num2))
mul=$((num1 * num2))

if [ "$num2" -eq 0 ]; then
   div="Cannot divide by zero"
else
   div=$((num1 / num2))
fi

echo ""
echo "Results:"
echo "$num1 + $num2 = $add"
echo "$num1 - $num2 = $sub"
echo "$num1 × $num2 = $mul"
echo "$num1 ÷ $num2 = $div"
